apiVersion: v1
description: A Helm chart for kube-ts-react-client
name: kube-ts-react-client
version: 1.0.0
appVersion: 1.2.3
home: https://cloud.docker.com/u/kubejs/repository/docker/kubejs/kube-ts-react-client
icon: https://avatars2.githubusercontent.com/u/47761918?s=200&v=4
sources:
  - https://github.com/kube-js/kube-ts-react-client
maintainers:
  - name: mariocoski
    email: mariuszrajczakowski@pm.me
    url: https://mariuszrajczakowski.me
